# 24-bit color support (TrueColor)
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Enable mouse for easy scrolling
set -g mouse on

#  Remap keybind to C-a (optional, more comfortable)
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Start windows and panes index at 1, not 0.
set -g base-index 1
setw -g pane-base-index 1

# Ensure window index numbers get reordered on delete.
set-option -g renumber-windows on

# Plugins (TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
