# 24-bit color support (TrueColor)
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Enable mouse for easy scrolling
set -g mouse on

#  Remap keybind to C-a (optional, more comfortable)
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Start windows and panes index at 1, not 0.
set -g base-index 1
setw -g pane-base-index 1

# Ensure window index numbers get reordered on delete.
set-option -g renumber-windows on


unbind r
bind r source-file ~/.tmux.conf

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position set-option

# Plugins (TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'


# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
# For TPM, instead use `
run ~/.tmux/plugins/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
